site_name: Flipper Documentation
site_url: https://reselim.github.io/flipper/
repo_name: Reselim/Flipper
repo_url: https://github.com/Reselim/Flipper

theme:
  name: material
  logo: simplified-logo.svg
  features:
    - navigation.instant
    - navigation.tabs
  palette:
    primary: blue
    accent: indigo

extra_css:
  - extra.css

nav:
  - Home: index.md
  - Installation: installation.md
  - Guides:
    - Introduction: guides/introduction.md
    - Example: guides/example.md
    - Springs: guides/springs.md
    - Hooks: guides/hooks.md
    - Extending Flipper: guides/extending-flipper.md
  - API Reference:
    - Flipper: api/flipper.md
    - Roact Flipper: api/roact-flipper.md